// src/pages/About.tsx
import React from 'react';
import Page  from '../components/Page';

export default function About(): React.JSX.Element {
  return (
    <Page>
      <h1>The McClain Family Cookbook</h1>
      <h2>About</h2>
      <p>
        This cookbook is a digitized version of the McClain Family Recipes book that was created in 2006. 
        The hope is that this will make the cookbook more accessible and allow us to easily add new recipes as time goes on.
      </p>
      <p>
        If you have any questions about how the cookbook works or ideas for how the cookbook can be improved, 
        send me an email at <a href="mailto:nathanblaubach@gmail.com">nathanblaubach@gmail.com</a>
      </p>
      <h2>Development</h2>
      <ul>
        {
          [
            {
              text: 'Source Code on GitHub (MIT)',
              url: 'https://github.com/nathanblaubach/cookbook-web-react'
            },
            {
              text: 'My Website',
              url: 'https://nathanblaubach.com'
            },
            {
              text: 'RealFaviconGenerator',
              url: 'https://realfavicongenerator.net/'
            }
          ].map(link => <li key={link.url}><a href={link.url}>{link.text}</a></li>)
        }
      </ul>
    </Page>
  );
}

// src/app/pages/about/about.component.ts
import { Component } from '@angular/core';

interface ExternalLink {
  text: string,
  url: string
}

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent {
  links: ExternalLink[] = [
    {
      text: 'Source Code on GitHub (MIT)',
      url: 'https://github.com/nathanblaubach/cookbook-web-angular'
    },
    {
      text: 'My Website',
      url: 'https://nathanblaubach.com'
    },
    {
      text: 'RealFaviconGenerator',
      url: 'https://realfavicongenerator.net/'
    }
  ];
}

<h1>The McClain Family Cookbook</h1>
<h2>About</h2>
<p>
  This cookbook is a digitized version of the McClain Family Recipes book that was created in 2006. 
  The hope is that this will make the cookbook more accessible and allow us to easily add new recipes as time goes on.
</p>
<p>
  If you have any questions about how the cookbook works or ideas for how the cookbook can be improved, 
  send me an email at <a href="mailto:nathanblaubach@gmail.com">nathanblaubach@gmail.com</a>
</p>
<h2>Development</h2>
<ul>
  <li *ngFor="let link of links">
    <a href={{link.url}}>{{link.text}}</a>
  </li>
</ul>
